### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by DavidBenko** [DavidBenko/Encrypted-Core-Data#1]
Make this a cocoapod

**Comment by giofid** [comment]
Hello. Thanks for this great project. 
I'd like to import it in my project via CocoaPods but I'm not able. 
I obtain  [!] Unable to find a specification for `Encrypted-Core-Data`. 
Could you help me? 
Thanks.

**Comment by DavidBenko** [comment]
I pulled in the cocoapods enhancement, so I haven't tried it. That said, I think your problem is that this repo has not been pushed to cocoapods trunk. Try using this in your pods file:

`pod 'Encrypted-Core-Data', :git => 'https://github.com/DavidBenko/Encrypted-Core-Data'`

Again, I have only used this by pulling in the files manually, so this is speculation.

**Comment by giofid** [comment]
It works!! 
Many thanks!!

**Comment by DavidBenko** [comment]
:+1:
